// Generated by CoffeeScript 1.8.0
var beget, explodeObject, factories, factory, getComparisonFactoryForOperator, isNotCriterion, isSpecialValue, prototypes, some,
  __slice = [].slice;

beget = function(proto, properties) {
  var key, object, value, _fn;
  object = Object.create(proto);
  if (properties != null) {
    _fn = function(key, value) {
      return object[key] = value;
    };
    for (key in properties) {
      value = properties[key];
      _fn(key, value);
    }
  }
  return object;
};

explodeObject = function(arrayOrObject) {
  var array, key, value, _fn;
  if (Array.isArray(arrayOrObject)) {
    return arrayOrObject;
  }
  array = [];
  _fn = function(key, value) {
    var object;
    object = {};
    object[key] = value;
    return array.push(object);
  };
  for (key in arrayOrObject) {
    value = arrayOrObject[key];
    _fn(key, value);
  }
  return array;
};

isSpecialValue = function(value) {
  return (value != null) && 'function' === typeof value.sql;
};

some = function(array, iterator, predicate, sentinel) {
  var i, length, result;
  if (iterator == null) {
    iterator = function(x) {
      return x;
    };
  }
  if (predicate == null) {
    predicate = function(x) {
      return x != null;
    };
  }
  if (sentinel == null) {
    sentinel = void 0;
  }
  i = 0;
  length = array.length;
  while (i < length) {
    result = iterator(array[i], i);
    if (predicate(result, i)) {
      return result;
    }
    i++;
  }
  return sentinel;
};

prototypes = {};

factories = {};

prototypes.base = {
  not: function() {
    return factories.not(this);
  },
  and: function(other) {
    return factories.and([this, other]);
  },
  or: function(other) {
    return factories.or([this, other]);
  }
};

prototypes.raw = beget(prototypes.base, {
  sql: function() {
    var i, params;
    if (!this._params) {
      return this._sql;
    }
    i = -1;
    params = this._params;
    return this._sql.replace(/\?/g, function() {
      i++;
      if (Array.isArray(params[i])) {
        return (params[i].map(function() {
          return "?";
        })).join(", ");
      } else {
        return "?";
      }
    });
  },
  params: function() {
    var _ref;
    if (this._params) {
      return (_ref = []).concat.apply(_ref, this._params);
    }
  }
});

factories.raw = function(sql, params) {
  return beget(prototypes.raw, {
    _sql: sql,
    _params: params
  });
};

prototypes.comparison = beget(prototypes.base, {
  sql: function() {
    if (isSpecialValue(this._value)) {
      return "" + this._key + " " + this._operator + " " + (this._value.sql());
    } else {
      return "" + this._key + " " + this._operator + " ?";
    }
  },
  params: function() {
    if (isSpecialValue(this._value)) {
      if ('function' === typeof this._value.params) {
        return this._value.params();
      } else {
        return [];
      }
    } else {
      return [this._value];
    }
  }
});

getComparisonFactoryForOperator = function(operator) {
  return function(key, value) {
    return beget(prototypes.comparison, {
      _key: key,
      _value: value,
      _operator: operator
    });
  };
};

factories.equal = getComparisonFactoryForOperator('=');

factories.notEqual = getComparisonFactoryForOperator('!=');

factories.lowerThan = getComparisonFactoryForOperator('<');

factories.lowerThanEqual = getComparisonFactoryForOperator('<=');

factories.greaterThan = getComparisonFactoryForOperator('>');

factories.greaterThanEqual = getComparisonFactoryForOperator('>=');

prototypes["null"] = beget(prototypes.base, {
  sql: function() {
    return "" + this._key + " IS " + (this._isNull ? '' : 'NOT ') + "NULL";
  },
  params: function() {
    return [];
  }
});

factories["null"] = function(k, isNull) {
  return beget(prototypes["null"], {
    _key: k,
    _isNull: isNull
  });
};

prototypes.not = beget(prototypes.base, {
  innerCriterion: function() {
    return this._criterion._criterion;
  },
  sql: function() {
    if (isNotCriterion(this._criterion)) {
      return this.innerCriterion().sql();
    } else {
      return "NOT (" + (this._criterion.sql()) + ")";
    }
  },
  params: function() {
    return this._criterion.params();
  }
});

isNotCriterion = function(c) {
  return prototypes.not.isPrototypeOf(c);
};

factories.not = function(criterion) {
  return beget(prototypes.not, {
    _criterion: criterion
  });
};

prototypes["in"] = beget(prototypes.base, {
  sql: function() {
    var questionMarks;
    questionMarks = [];
    this._values.forEach(function() {
      return questionMarks.push('?');
    });
    return "" + this._key + " " + this._operator + " (" + (questionMarks.join(', ')) + ")";
  },
  params: function() {
    return this._values;
  }
});

factories["in"] = function(key, values) {
  return beget(prototypes["in"], {
    _key: key,
    _values: values,
    _operator: 'IN'
  });
};

factories.notIn = function(key, values) {
  return beget(prototypes["in"], {
    _key: key,
    _values: values,
    _operator: 'NOT IN'
  });
};

prototypes.combination = beget(prototypes.base, {
  sql: function() {
    return this._criteria.map(function(c) {
      return "(" + (c.sql()) + ")";
    }).join(" " + this._operator + " ");
  },
  params: function() {
    var params;
    params = [];
    this._criteria.forEach(function(c) {
      return params = params.concat(c.params());
    });
    return params;
  }
});

factories.and = function(criteria) {
  return beget(prototypes.combination, {
    _criteria: criteria,
    _operator: 'AND'
  });
};

factories.or = function(criteria) {
  return beget(prototypes.combination, {
    _criteria: criteria,
    _operator: 'OR'
  });
};

module.exports = factory = function() {
  var emptyArrayParam, first, hasModifier, innerValue, isEmptyArray, key, keyCount, keys, modifier, rest, type, value;
  first = arguments[0], rest = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  type = typeof first;
  if (!('string' === type || 'object' === type)) {
    throw new Error("string or object expected as first argument\nbut " + type + " given");
  }
  if (type === 'string') {
    isEmptyArray = function(x) {
      return Array.isArray(x) && x.length === 0;
    };
    emptyArrayParam = some(rest, function(x, i) {
      return {
        x: x,
        i: i
      };
    }, function(_arg) {
      var i, x;
      x = _arg.x, i = _arg.i;
      return isEmptyArray(x);
    });
    if (emptyArrayParam != null) {
      throw new Error("params[" + emptyArrayParam.i + "] is an empty array");
    }
    return factories.raw(first, rest);
  }
  if (Array.isArray(first)) {
    if (first.length === 0) {
      throw new Error('empty criterion');
    }
    return factories.and(first.map(factory));
  }
  keyCount = Object.keys(first).length;
  if (0 === keyCount) {
    throw new Error('empty criterion');
  }
  if (keyCount > 1) {
    return factories.and(explodeObject(first).map(factory));
  }
  key = Object.keys(first)[0];
  value = first[key];
  if (value == null) {
    throw new Error("value undefined or null for key " + key);
  }
  if (key === '$or') {
    return factories.or(explodeObject(value).map(factory));
  }
  if (key === '$not') {
    return factories.not(factory(value));
  }
  if ('object' !== typeof value) {
    return factories.equal(key, value);
  }
  if (Array.isArray(value)) {
    if (value.length === 0) {
      throw Error('in with empty array');
    }
    return factories["in"](key, value);
  }
  keys = Object.keys(value);
  modifier = keys[0];
  hasModifier = keys.length === 1 && 0 === modifier.indexOf('$');
  if (!hasModifier) {
    return factories.equal(key, value);
  }
  innerValue = value[modifier];
  if (innerValue == null) {
    throw new Error("value undefined or null for key " + key + " and modifier " + modifier);
  }
  switch (modifier) {
    case '$nin':
      if (innerValue.length === 0) {
        throw Error('$nin with empty array');
      }
      return factories.notIn(key, innerValue);
    case '$lt':
      return factories.lowerThan(key, innerValue);
    case '$lte':
      return factories.lowerThanEqual(key, innerValue);
    case '$gt':
      return factories.greaterThan(key, innerValue);
    case '$gte':
      return factories.greaterThanEqual(key, innerValue);
    case '$ne':
      return factories.notEqual(key, innerValue);
    case '$null':
      return factories["null"](key, innerValue);
    default:
      throw new Error("unknown modifier: " + modifier);
  }
};
